# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=256)),
                ('image', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField()),
                ('edited_at', models.DateTimeField(null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.Profile')),
            ],
        ),
    ]
