# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='blocker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_made', to='profiles.Profile'),
        ),
    ]
